spring:
  jpa:
    show-sql: true
  application:
    name: security
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sba?useSSL=true&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
server:
  port: 8081
  max-http-header-size: 15360
  servlet:
    context-path: /jwt
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

logging:
  level:
    root: INFO
    org:
      springframework:
        security: DEBUG
        web: ERROR
      hibernate:
        SQL: DEBUG
sba.security.jwt.secret: jwtGrokonezSecretKey
sba.security.jwt.jwtExpiration: 86400

